//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.enrollments = new HashSet<enrollment>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string course_description { get; set; }
        public System.DateTime course_start_date { get; set; }
        public System.DateTime course_end_date { get; set; }
        public int intitial_seats { get; set; }
        public Nullable<float> currentseats { get; set; }
        public Nullable<int> trainer_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> coursecategory { get; set; }
        public string approvedstatus { get; set; }
    
        public virtual coursecategory coursecategory1 { get; set; }
        public virtual Trainer Trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enrollment> enrollments { get; set; }
    }
}
