//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Women_EmpowerementEntities : DbContext
    {
        public Women_EmpowerementEntities()
            : base("name=Women_EmpowerementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<coursecategory> coursecategories { get; set; }
        public virtual DbSet<enrollment> enrollments { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<ngo> ngoes { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<woman> women { get; set; }
    }
}
