//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollment
    {
        public int women_id { get; set; }
        public int course_id { get; set; }
        public Nullable<System.DateTime> enrollment_date { get; set; }
        public string approval_status { get; set; }
    
        public virtual course course { get; set; }
        public virtual woman woman { get; set; }
    }
}
