//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedback_id { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }
        public string feedback_description { get; set; }
        public Nullable<int> women_id { get; set; }
    
        public virtual woman woman { get; set; }
    }
}
