//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ngo()
        {
            this.Trainers = new HashSet<Trainer>();
        }
    
        public int ngo_id { get; set; }
        public string ngo_name { get; set; }
        public string contact_person { get; set; }
        public string ngo_contact_number { get; set; }
        public string ngo_address { get; set; }
        public string ngo_city { get; set; }
        public string ngo_state { get; set; }
        public string ngo_description { get; set; }
        public string ngo_email { get; set; }
        public string ngo_password { get; set; }
        public string ngo_supportingdocument { get; set; }
        public Nullable<bool> status { get; set; }
        public string approvedstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainer> Trainers { get; set; }
    }
}
